# Generated by Django 5.0.6 on 2024-06-23 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='продукт')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='картинка 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='картинка 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='картинка 3')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.subcategory', verbose_name='подкатегория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
